### ISSUE TITLE
Data pipeline broken

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#263]
CPI pipeline fails with the following

```sh
Running stage 'scripts/cpi/dvc.yaml:prepare':                                                                                 
> PYTHONPATH=. python3 scripts/cpi/prepare.py
Traceback (most recent call last):
  File "/media/data/code/oi/yff-data/scripts/cpi/prepare.py", line 136, in <module>
    bar = bar_chart(data, n).drop(index=["Furniture, household equipment & maintenance",
  File "/media/data/code/oi/yff-data/scripts/cpi/prepare.py", line 105, in bar_chart
    indicator = pd.DataFrame(data={'indicator': indicators, 'sign': sgn}, index=index)
  File "/home/giles/.local/share/virtualenvs/yff-data-ansOWYcy/lib/python3.10/site-packages/pandas/core/frame.py", line 709, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/giles/.local/share/virtualenvs/yff-data-ansOWYcy/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 481, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/home/giles/.local/share/virtualenvs/yff-data-ansOWYcy/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 120, in arrays_to_mgr
    arrays, refs = _homogenize(arrays, index, dtype)
  File "/home/giles/.local/share/virtualenvs/yff-data-ansOWYcy/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 608, in _homogenize
    com.require_length_match(val, index)
  File "/home/giles/.local/share/virtualenvs/yff-data-ansOWYcy/lib/python3.10/site-packages/pandas/core/common.py", line 576, in require_length_match
    raise ValueError(
ValueError: Length of values (2) does not match length of index (3)
```

**Comment by gilesdring** [comment]
If not positive, CPI indicator `sgn` array is too short, hence causes `ValueError` above

**Comment by gilesdring** [comment]
See above, @luke-strange

**Comment by luke-strange** [comment]
@gilesdring thanks!
