### ISSUE TITLE
PostCSS fails under WSL

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/yff-data#6]
Some error related to sqlite locking

@slowe Could you paste stack trace / log into here.

**Comment by slowe** [comment]
Here's the full listing
```
Warning deno task is unstable and may drastically change in the future
Task serve deno task lume -s
Warning deno task is unstable and may drastically change in the future
Task lume deno eval "import 'lume/task.ts'" -- "-s"
Download https://deno.land/x/lume@v1.10.1/task.ts
Download https://deno.land/x/lume@v1.10.1/ci.ts
Download https://deno.land/x/lume@v1.10.1/core/utils.ts
Download https://deno.land/x/lume@v1.10.1/deps/base64.ts
Download https://deno.land/x/lume@v1.10.1/deps/colors.ts
Download https://deno.land/x/lume@v1.10.1/deps/flags.ts
Download https://deno.land/std@0.148.0/encoding/base64.ts
Download https://deno.land/std@0.148.0/flags/mod.ts
Download https://deno.land/std@0.148.0/fmt/colors.ts
Download https://deno.land/x/lume@v1.10.1/deps/dom.ts
Download https://deno.land/x/lume@v1.10.1/deps/fs.ts
Download https://deno.land/x/lume@v1.10.1/deps/path.ts
Download https://deno.land/x/lume@v1.10.1/core/errors.ts
Download https://deno.land/std@0.148.0/_util/assert.ts
Download https://deno.land/std@0.148.0/path/mod.ts
Download https://deno.land/std@0.148.0/fs/mod.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/deno-dom-wasm.ts
Download https://deno.land/x/lume@v1.10.1/core.ts
Download https://deno.land/std@0.148.0/fs/copy.ts
Download https://deno.land/std@0.148.0/fs/empty_dir.ts
Download https://deno.land/std@0.148.0/fs/ensure_dir.ts
Download https://deno.land/std@0.148.0/fs/ensure_file.ts
Download https://deno.land/std@0.148.0/fs/ensure_link.ts
Download https://deno.land/std@0.148.0/fs/ensure_symlink.ts
Download https://deno.land/std@0.148.0/fs/eol.ts
Download https://deno.land/std@0.148.0/fs/exists.ts
Download https://deno.land/std@0.148.0/fs/expand_glob.ts
Download https://deno.land/std@0.148.0/fs/move.ts
Download https://deno.land/std@0.148.0/fs/walk.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/build/deno-wasm/deno-wasm.js
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/api.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/parser.ts
Download https://deno.land/std@0.148.0/_util/os.ts
Download https://deno.land/std@0.148.0/path/_interface.ts
Download https://deno.land/std@0.148.0/path/common.ts
Download https://deno.land/std@0.148.0/path/glob.ts
Download https://deno.land/std@0.148.0/path/posix.ts
Download https://deno.land/std@0.148.0/path/separator.ts
Download https://deno.land/std@0.148.0/path/win32.ts
Download https://deno.land/x/lume@v1.10.1/core/component_loader.ts
Download https://deno.land/x/lume@v1.10.1/core/data_loader.ts
Download https://deno.land/x/lume@v1.10.1/core/events.ts
Download https://deno.land/x/lume@v1.10.1/core/filesystem.ts
Download https://deno.land/x/lume@v1.10.1/core/formats.ts
Download https://deno.land/x/lume@v1.10.1/core/includes_loader.ts
Download https://deno.land/x/lume@v1.10.1/core/logger.ts
Download https://deno.land/x/lume@v1.10.1/core/page_loader.ts
Download https://deno.land/x/lume@v1.10.1/core/processors.ts
Download https://deno.land/x/lume@v1.10.1/core/reader.ts
Download https://deno.land/x/lume@v1.10.1/core/renderer.ts
Download https://deno.land/x/lume@v1.10.1/core/scopes.ts
Download https://deno.land/x/lume@v1.10.1/core/scripts.ts
Download https://deno.land/x/lume@v1.10.1/core/server.ts
Download https://deno.land/x/lume@v1.10.1/core/site.ts
Download https://deno.land/x/lume@v1.10.1/core/source.ts
Download https://deno.land/x/lume@v1.10.1/core/watcher.ts
Download https://deno.land/x/lume@v1.10.1/core/writer.ts
Download https://deno.land/std@0.148.0/fs/_util.ts
Download https://deno.land/std@0.148.0/_deno_unstable.ts
Download https://deno.land/std@0.148.0/path/_constants.ts
Download https://deno.land/std@0.148.0/path/_util.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/deserialize.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/document-fragment.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/document.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/dom-parser.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/element.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/elements/html-template-element.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/html-collection.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/node-list.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/node.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/selectors/selectors.ts
Download https://deno.land/x/lume@v1.10.1/deps/http.ts
Download https://deno.land/x/lume@v1.10.1/core/loaders/text.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/constructor-lock.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/utils.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/utils-types.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/selectors/nwsapi-types.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/selectors/sizzle-types.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/selectors/custom-api.ts
Download https://deno.land/std@0.148.0/http/file_server.ts
Download https://deno.land/std@0.148.0/http/server.ts
Download https://deno.land/x/lume@v1.10.1/deps/front_matter.ts
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/selectors/sizzle.js
Download https://deno.land/x/deno_dom@v0.1.32-alpha/src/dom/selectors/nwsapi.js
Download https://deno.land/std@0.148.0/encoding/hex.ts
Download https://deno.land/std@0.148.0/media_types/mod.ts
Download https://deno.land/std@0.148.0/http/http_status.ts
Download https://deno.land/std@0.148.0/http/util.ts
Download https://deno.land/std@0.148.0/encoding/front_matter.ts
Download https://deno.land/std@0.148.0/async/mod.ts
Download https://deno.land/std@0.148.0/media_types/_util.ts
Download https://deno.land/std@0.148.0/media_types/vendor/mime-db.v1.52.0.ts
Download https://deno.land/std@0.148.0/async/abortable.ts
Download https://deno.land/std@0.148.0/async/deadline.ts
Download https://deno.land/std@0.148.0/async/debounce.ts
Download https://deno.land/std@0.148.0/async/deferred.ts
Download https://deno.land/std@0.148.0/async/delay.ts
Download https://deno.land/std@0.148.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.148.0/async/pool.ts
Download https://deno.land/std@0.148.0/async/tee.ts
Download https://deno.land/std@0.148.0/encoding/yaml.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/parse.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/schema.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/schema/mod.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/stringify.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/utils.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/schema/core.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/schema/default.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/schema/extended.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/schema/failsafe.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/schema/json.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/dumper/dumper.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/dumper/dumper_state.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/error.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/loader/loader.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/loader/loader_state.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/mod.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/state.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/mark.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/binary.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/bool.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/float.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/function.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/int.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/map.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/merge.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/nil.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/omap.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/pairs.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/regexp.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/seq.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/set.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/str.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/timestamp.ts
Download https://deno.land/std@0.148.0/encoding/_yaml/type/undefined.ts
Download https://deno.land/std@0.148.0/io/buffer.ts
Download https://deno.land/std@0.148.0/bytes/bytes_list.ts
Download https://deno.land/std@0.148.0/bytes/mod.ts
Download https://deno.land/std@0.148.0/io/types.d.ts
Download https://deno.land/std@0.148.0/bytes/equals.ts
Download https://deno.land/x/lume@v1.10.1/cli.ts
Download https://deno.land/x/lume@v1.10.1/cli/build.ts
Download https://deno.land/x/lume@v1.10.1/cli/import_map.ts
Download https://deno.land/x/lume@v1.10.1/cli/init.ts
Download https://deno.land/x/lume@v1.10.1/cli/run.ts
Download https://deno.land/x/lume@v1.10.1/cli/upgrade.ts
Download https://deno.land/x/lume@v1.10.1/cli/vendor.ts
Download https://deno.land/x/lume@v1.10.1/deps/cliffy.ts
Download https://deno.land/x/lume@v1.10.1/middlewares/logger.ts
Download https://deno.land/x/lume@v1.10.1/middlewares/no_cache.ts
Download https://deno.land/x/lume@v1.10.1/middlewares/not_found.ts
Download https://deno.land/x/lume@v1.10.1/middlewares/reload.ts
Download https://deno.land/x/lume@v1.10.1/cli/utils.ts
Download https://deno.land/x/lume@v1.10.1/middlewares/reload_client.js
Download https://deno.land/x/lume@v1.10.1/mod.ts
Download https://deno.land/x/lume@v1.10.1/plugins/json.ts
Download https://deno.land/x/lume@v1.10.1/plugins/markdown.ts
Download https://deno.land/x/lume@v1.10.1/plugins/modules.ts
Download https://deno.land/x/lume@v1.10.1/plugins/nunjucks.ts
Download https://deno.land/x/lume@v1.10.1/plugins/paginate.ts
Download https://deno.land/x/lume@v1.10.1/plugins/search.ts
Download https://deno.land/x/lume@v1.10.1/plugins/url.ts
Download https://deno.land/x/lume@v1.10.1/plugins/yaml.ts
Download https://deno.land/x/lume@v1.10.1/deps/nunjucks.ts
Download https://deno.land/x/lume@v1.10.1/core/loaders/yaml.ts
Download https://deno.land/x/lume@v1.10.1/core/loaders/module.ts
Download https://deno.land/x/lume@v1.10.1/deps/markdown_it.ts
Download https://deno.land/x/lume@v1.10.1/core/loaders/json.ts
Download https://deno.land/x/lume@v1.10.1/deps/yaml.ts
Loading config file /mnt/c/Users/StuartLowe/Documents/ODILeeds/projects/yff/yff-wireframe/_config.js

Download https://deno.land/x/lume@v1.10.1/plugins/base_path.ts
Download https://deno.land/x/lume@v1.10.1/plugins/netlify_cms.ts
Download https://deno.land/x/lume@v1.10.1/plugins/postcss.ts
Download https://deno.land/x/lume@v1.10.1/plugins/resolve_urls.ts
Download https://deno.land/x/lume@v1.10.1/plugins/slugify_urls.ts
Download https://deno.land/std@0.82.0/encoding/yaml.ts
Download https://deno.land/std@0.82.0/fs/copy.ts
Download https://deno.land/std@0.82.0/encoding/csv.ts
Download https://deno.land/x/lume@v1.10.1/plugins/modify_urls.ts
Download https://deno.land/x/lume@v1.10.1/deps/postcss.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/parse.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/schema.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/schema/mod.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/stringify.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type.ts
Download https://deno.land/std@0.82.0/_util/assert.ts
Download https://deno.land/std@0.82.0/_util/os.ts
Download https://deno.land/std@0.82.0/path/mod.ts
Download https://deno.land/std@0.82.0/fs/_util.ts
Download https://deno.land/std@0.82.0/fs/ensure_dir.ts
Download https://deno.land/std@0.82.0/io/bufio.ts
Download https://deno.land/std@0.82.0/io/readers.ts
Download https://deno.land/std@0.82.0/textproto/mod.ts
Download https://deno.land/std@0.82.0/encoding/csv_stringify.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/loader/loader.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/loader/loader_state.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/error.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/utils.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/schema/core.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/schema/default.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/schema/failsafe.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/schema/json.ts
Download https://deno.land/std@0.82.0/path/_interface.ts
Download https://deno.land/std@0.82.0/path/common.ts
Download https://deno.land/std@0.82.0/path/glob.ts
Download https://deno.land/std@0.82.0/path/posix.ts
Download https://deno.land/std@0.82.0/path/separator.ts
Download https://deno.land/std@0.82.0/path/win32.ts
Download https://deno.land/std@0.82.0/bytes/mod.ts
Download https://deno.land/std@0.82.0/encoding/utf8.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/dumper/dumper.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/dumper/dumper_state.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/mark.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/state.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/mod.ts
Download https://deno.land/std@0.82.0/path/_constants.ts
Download https://deno.land/std@0.82.0/path/_util.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/binary.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/bool.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/float.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/int.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/map.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/merge.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/nil.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/omap.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/pairs.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/seq.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/set.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/str.ts
Download https://deno.land/std@0.82.0/encoding/_yaml/type/timestamp.ts
Error 'locking protocol' contains boxed error of unknown type:
  SqliteFailure(Error { code: FileLockingProtocolFailed, extended_code: 15 }, Some("locking protocol"))
  Error { code: FileLockingProtocolFailed, extended_code: 15 }

Error: locking protocol
    at Object.opSync (deno:core/01_core.js:170:12)
    at Storage.getItem (deno:ext/webstorage/01_webstorage.js:71:19)
    at Object.get (deno:ext/webstorage/01_webstorage.js:120:25)
    at config (https://cdn.jsdelivr.net/npm/postcss-nesting@10.0.2/dist/index.deno.mjs:1545:40)
    at deprecate (https://cdn.jsdelivr.net/npm/postcss-nesting@10.0.2/dist/index.deno.mjs:1508:7)
    at (https://cdn.jsdelivr.net/npm/postcss-nesting@10.0.2/dist/index.deno.mjs:1579:39)
    at (https://cdn.jsdelivr.net/npm/postcss-nesting@10.0.2/dist/index.deno.mjs:2065:2)
```

**Comment by gilesdring** [comment]
Oooh.. might be something like this...

https://github.com/denoland/deno/issues/13141

Could you try uncommenting the postcss code in the `_config.js` to reintroduce then run `sudo deno task serve`
